[build-system]
build-backend = "hatchling.build"

requires = [
  "hatch-vcs",
  "hatchling",
]

[project]
name = "virtual_tiff"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = []
authors = [
  { name = "Max Jones", email = "14077947+maxrjones@users.noreply.github.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]

dependencies = [
    "obstore",
    "async_tiff",
    "virtualizarr",
    "imagecodecs",
    "imagecodecs-numcodecs",
    "zarr",
]

# Dependency sets under dependencies-groups are NOT available via PyPI
[dependency-groups]
docs = [
  "sphinx",
  "myst_nb",
  "pydata_sphinx_theme",
  "sphinx_copybutton",
  "sphinx_design",
  "sphinx_togglebutton",
  "sphinx-autobuild>=2021.3.14",
  "sphinx-autodoc-typehints",
]
dev = [
  "codecov",
  "netcdf4",
  "mypy",
  "pandas-stubs",
  "pooch",
  "pre-commit",
  "pytest",
  "pytest-asyncio",
  "pytest-cov",
  "pytest-mypy",
  "pytest-xdist",
  "ruff",
  "s3fs",
  "lithops",
  "dask",
  "rioxarray",
  "rasterio",
  "earthaccess",
  "xarray",
]

[tool.coverage.run]
source_pkgs = [""]
branch = true
parallel = true
omit = []

[tool.uv.sources]
virtualizarr = { git = "https://github.com/zarr-developers/VirtualiZarr.git" }
obstore = { git = "https://github.com/developmentseed/obstore", subdirectory="obstore", rev = "848e7c99972f9e13c185dd1f84b1194f5621015f" }
async_tiff = { git = "https://github.com/developmentseed/async-tiff", subdirectory="python", rev = "c720f01235ea706d8fb926909eb68409e07149ed" }
zarr = { git = "https://github.com/maxrjones/zarr-python", rev ="41ad842768a754dbb80c30d8486b40970d0bc74c" }

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
packages = [
  "src/virtual_tiff",
]

[project.entry-points."zarr.codecs"]
"imagecodecs.delta" = "virtual_tiff.imagecodecs:Delta"
"imagecodecs.lzw" = "virtual_tiff.imagecodecs:LZW"
"imagecodecs.zstd" = "virtual_tiff.imagecodecs:Zstd"
"imagecodecs.deflate" = "virtual_tiff.imagecodecs:Deflate"

